(ns polylith.clj.core.path-finder.test-data
  (:require [clojure.test :refer :all]))

(def dep-entries [{:profile? false, :test? false, :lib-dep ["org.clojure/clojure" {:mvn/version "1.10.1"}]}
                  {:profile? false, :test? false, :lib-dep ["org.clojure/tools.deps"{:mvn/version "0.16.1264"}]}
                  {:profile? false, :test? true, :lib-dep ["zprint" #:mvn{:version "0.4.15"}]}
                  {:profile? true, :test? false, :lib-dep ["net.mikera/core.matrix" {:mvn/version "0.62.0"}]}])

(def path-entries [{:exists?    true
                    :name       "cli"
                    :path       "bases/cli/resources"
                    :profile?   false
                    :source-dir "resources"
                    :test?      false
                    :type       :base}
                   {:exists?    true
                    :name       "cli"
                    :path       "bases/cli/src"
                    :profile?   false
                    :source-dir "src"
                    :test?      false
                    :type       :base}
                   {:exists?    true
                    :name       "address"
                    :path       "libs/address/resources"
                    :profile?   false
                    :source-dir "resources"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "address"
                    :path       "libs/address/src"
                    :profile?   false
                    :source-dir "src"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "database"
                    :path       "libs/database/resources"
                    :profile?   false
                    :source-dir "resources"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "database"
                    :path       "libs/database/src"
                    :profile?   false
                    :source-dir "src"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "invoicer"
                    :path       "libs/invoicer/resources"
                    :profile?   false
                    :source-dir "resources"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "invoicer"
                    :path       "libs/invoicer/src"
                    :profile?   false
                    :source-dir "src"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "purchaser"
                    :path       "libs/purchaser/resources"
                    :profile?   false
                    :source-dir "resources"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "purchaser"
                    :path       "libs/purchaser/src"
                    :profile?   false
                    :source-dir "src"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "user"
                    :path       "libs/user/resources"
                    :profile?   false
                    :source-dir "resources"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "user"
                    :path       "libs/user/src"
                    :profile?   false
                    :source-dir "src"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "development"
                    :path       "development/src"
                    :profile?   false
                    :source-dir "src"
                    :test?      false
                    :type       :project}
                   {:exists?    true
                    :name       "cli"
                    :path       "bases/cli/test"
                    :profile?   false
                    :source-dir "test"
                    :test?      true
                    :type       :base}
                   {:exists?    true
                    :name       "address"
                    :path       "libs/address/test"
                    :profile?   false
                    :source-dir "test"
                    :test?      true
                    :type       :lib}
                   {:exists?    true
                    :name       "database"
                    :path       "libs/database/test"
                    :profile?   false
                    :source-dir "test"
                    :test?      true
                    :type       :lib}
                   {:exists?    true
                    :name       "invoicer"
                    :path       "libs/invoicer/test"
                    :profile?   false
                    :source-dir "test"
                    :test?      true
                    :type       :lib}
                   {:exists?    true
                    :name       "purchaser"
                    :path       "libs/purchaser/test"
                    :profile?   false
                    :source-dir "test"
                    :test?      true
                    :type       :lib}
                   {:exists?    true
                    :name       "user"
                    :path       "libs/user/test"
                    :profile?   false
                    :source-dir "test"
                    :test?      true
                    :type       :lib}
                   {:exists?    true
                    :name       "invoice"
                    :path       "projects/invoice/test"
                    :profile?   false
                    :source-dir "test"
                    :test?      true
                    :type       :project}
                   {:exists?    true
                    :name       "development"
                    :path       "development/test"
                    :profile?   false
                    :source-dir "test"
                    :test?      true
                    :type       :project}
                   {:exists?    true
                    :name       "user"
                    :path       "libs/user/resources"
                    :profile?   true
                    :source-dir "resources"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "user"
                    :path       "libs/user/src"
                    :profile?   true
                    :source-dir "src"
                    :test?      false
                    :type       :lib}
                   {:exists?    true
                    :name       "user"
                    :path       "libs/user/test"
                    :profile?   true
                    :source-dir "test"
                    :test?      true
                    :type       :lib}])
